//! Contents provided to proc macros.
//!
//! Users should not directly use any content here.

pub mod macro_utils {
    // When generating code, using `std` or `alloc` directly is unsafe.
    // Users may be in a `no_std` env or not displaying imported `alloc`.
    //
    // Therefore, proc-macro crate will use this path.
    pub use ::vc_utils::prelude::{Box, Cow, ToOwned, ToString};

    pub use crate::impls::concat as __concat;
}

// use for `reflect_clone` impl
pub fn __reflect_clone_field<T: crate::Reflect + crate::info::TypePath>(
    source: &T,
) -> Result<T, crate::ops::ReflectCloneError> {
    if let Ok(t) = source.reflect_clone()
        && let Ok(val) = t.take::<T>()
    {
        Ok(val)
    } else {
        Err(crate::ops::ReflectCloneError::NotSupport {
            type_path: T::type_path().into(),
        })
    }
}

#[cfg(feature = "auto_register")]
pub mod auto_register {
    use crate::{
        derive::Reflect,
        registry::{GetTypeMeta, TypeMeta, TypeRegistry},
    };
    pub use inventory;

    pub trait __RegisterType {
        fn __register(_registry: &mut TypeRegistry) {}
    }

    impl<T: GetTypeMeta> __RegisterType for T {
        fn __register(registry: &mut TypeRegistry) {
            registry.register::<T>();
        }
    }

    pub struct __AutoRegisterFunc(pub fn(&mut TypeRegistry));

    inventory::collect!(__AutoRegisterFunc);

    pub fn __register_types(registry: &mut TypeRegistry) {
        #[cfg(target_family = "wasm")]
        wasm_support::init();
        for registry_fn in inventory::iter::<__AutoRegisterFunc> {
            registry_fn.0(registry);
        }
    }

    #[cfg(target_family = "wasm")]
    mod wasm_support {
        use vc_os::sync::OnceFlag;

        static INIT_ONCE: OnceFlag = OnceFlag::new();

        #[expect(unsafe_code, reason = "This function is generated by linker.")]
        unsafe extern "C" {
            fn __wasm_call_ctors();
        }

        /// This function must be called before using [`inventory::iter`]
        /// on [`AutomaticReflectRegistrations`] to run constructors on all platforms.
        pub fn init() {
            if INIT_ONCE.set() {
                // SAFETY:
                // This will call constructors on wasm platforms at most once.
                //
                // See: https://docs.rs/inventory/latest/inventory/#webassembly-and-constructors
                #[expect(unsafe_code, reason = "This function must be called to on wasm.")]
                unsafe {
                    __wasm_call_ctors();
                }
            }
        }
    }

    // Used to determine if automatic registration is working properly.
    #[derive(Reflect)]
    #[reflect(auto_register)]
    #[reflect(GetTypeMeta = false, FromReflect = false)]
    pub struct __AvailFlag;

    impl GetTypeMeta for __AvailFlag {
        fn get_type_meta() -> TypeMeta {
            TypeMeta::of::<Self>()
        }
    }
}
